'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")>  _
Partial Friend NotInheritable Class SpainConfig
    Inherits Global.System.Configuration.ApplicationSettingsBase

    Private Shared defaultInstance As SpainConfig = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New SpainConfig()),SpainConfig)

    Public Shared ReadOnly Property [Default]() As SpainConfig
        Get
            Return defaultInstance
        End Get
    End Property

    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("TORRECID")>  _
    Public ReadOnly Property Domain() As String
        Get
            Return CType(Me("Domain"),String)
        End Get
    End Property

    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("S")>  _
    Public ReadOnly Property CompanyCode() As String
        Get
            Return CType(Me("CompanyCode"),String)
        End Get
    End Property

    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0000")>  _
    Public ReadOnly Property AppCode() As String
        Get
            Return CType(Me("AppCode"),String)
        End Get
    End Property

    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("GESMARGEN")>  _
    Public ReadOnly Property AppName() As String
        Get
            Return CType(Me("AppName"),String)
        End Get
    End Property

    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\\fileserveres\apps\Visual\config\oracle")>  _
    Public ReadOnly Property TNS_ADMIN() As String
        Get
            Return CType(Me("TNS_ADMIN"),String)
        End Get
    End Property

    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("TORRECID, S.A.")>  _
    Public ReadOnly Property CompanyName() As String
        Get
            Return CType(Me("CompanyName"),String)
        End Get
    End Property

    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\\atenea\APPS\Visual\config\v2\logos\forms\torrecid-group.jpg")>  _
    Public ReadOnly Property CompanyLogoLocation() As String
        Get
            Return CType(Me("CompanyLogoLocation"),String)
        End Get
    End Property

End Class
